### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by efe-erkaslan** [How-Bout-No/Outvoted#104] opened 2021-11-14 19:49 UTC
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run without mods like Optifine (if needed)
[ ] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**

**To Reproduce**
1. spawn copper golem with oxidation
2. right click with axe
3. crash

**Screenshots/Logs**
https://pastebin.com/uJw9B6kQ
**Version (please complete the following information):**
 - Minecraft Version 1.17.1
 - Modloader Fabric
 - Mod Version 1.5.0-beta.3

**Additional context**
works fine in SP

**Comment by How-Bout-No** [comment] 2021-11-14 19:52
Duplicate of #102

**Closed as completed by How-Bout-No** 2021-11-14 19:52 UTC
Labels: bug, duplicate
