### ISSUE TITLE
Rendering errors due to biome variants

### ISSUE THREAD

**Issue by Warbringer12** [How-Bout-No/Outvoted#12] opened 2020-11-23 03:00 UTC
1. loaded into world

If applicable, add screenshots to help explain your problem, or logs from Pastebin or similar.
[crash-2020-11-22_18.44.14-client.txt](https://github.com/How-Bout-No/Outvoted/files/5580922/crash-2020-11-22_18.44.14-client.txt)
[debug.log](https://github.com/How-Bout-No/Outvoted/files/5580928/debug.log)
[latest.log](https://github.com/How-Bout-No/Outvoted/files/5580929/latest.log)

**Version (please complete the following information):**
 - Minecraft Version 1.16.4
 - Mod Version  b0.4.1

**Comment by How-Bout-No** [comment] 2020-11-23 03:40
Judging by the log it looks like you're running Java 14, which can cause issues with Minecraft.
Are you able to try running Java 8 instead and try to see if the issues still stands?

**Comment by Keb911** [comment] 2020-11-23 18:13
Can confirm it happens in java 8 too,

Java 1.8.0_271
Forge 35.1.2
Outvoted b0.4.1

[crash-2020-11-22_22.52.21-client.txt](https://github.com/How-Bout-No/Outvoted/files/5584912/crash-2020-11-22_22.52.21-client.txt)

**Comment by How-Bout-No** [comment] 2020-11-23 22:34
Interesting. Could both of you @Warbringer12 and @Keb911 try the jar in the attached zip file and report back if the issue still occurs? Thanks!
[outvoted-1.16.3-b0.4.1-a.jar.zip](https://github.com/How-Bout-No/Outvoted/files/5586137/outvoted-1.16.3-b0.4.1-a.jar.zip)

**Comment by Keb911** [comment] 2020-11-23 23:37
The issue no longer occurs with that version, thanks.

**Comment by How-Bout-No** [comment] 2020-11-23 23:44
Great! I'll be pushing out an official update soon.

**Comment by Charwten** [comment] 2020-11-24 17:15
I downloaded the file you sent but I keep getting the same error. I'm running on 1.16.3 so I don't know if that can be an issue

**Comment by How-Bout-No** [comment] 2020-11-24 17:22
> I downloaded the file you sent but I keep getting the same error. I'm running on 1.16.3 so I don't know if that can be an issue

Oh, really? Are you getting the same error in the log or is it separate? So far everyone else has had success with it and I'm unable to replicate the issue on my end before + after fix for some odd reason.

**Comment by Charwten** [comment] 2020-11-24 17:26
> > I downloaded the file you sent but I keep getting the same error. I'm running on 1.16.3 so I don't know if that can be an issue
> 
> @Charwten
> Oh, really? Are you getting the same error in the log or is it separate? So far everyone else has had success with it and I'm unable to replicate the issue on my end before + after fix for some odd reason.

Yeahh I just get the same error of this.
[crash-2020-11-24_11.23.10-fml.txt](https://github.com/How-Bout-No/Outvoted/files/5591610/crash-2020-11-24_11.23.10-fml.txt)

**Comment by How-Bout-No** [comment] 2020-11-24 17:41
Interesting...
I have already stated that I've never been able to replicate the issue in the first place and just went out on a whim on a line of code that'd fix the problem. I'll do some further testing to see if I can replicate it.

**Comment by Charwten** [comment] 2020-11-24 17:47
Alright. Sorry to bother you if this is just out of the blue for you but thank you nonetheless for the help :)

**Comment by How-Bout-No** [comment] 2020-11-24 17:49
No worries, it's fine. The last thing I want is game breaking bugs.

**Comment by Keb911** [comment] 2020-11-24 23:51
I thought of something. Are @Warbringer12 and @Charwten on a server? I experienced the original issue on a friend's server, but only tested b0.4.1a on a single player world. I wonder if this only happens on a server?

**Comment by Charwten** [comment] 2020-11-25 01:48
@Keb911 Yeah! I play with some friends on a server and I had the same exact thing! I tried the b0.4.1a file on single player and it worked but didn't on multiplayer

**Comment by How-Bout-No** [comment] 2020-11-25 01:53
Ok that helps. So I assume they don't use the hotfixed jar on the server. I assumed since the crash was related just to the rendering it would only be a client-side fix but it seems to be more than that. I still can't reproduce the crash on my end and I'm unsure as to why, must be something with my dev environment.
Sorry for bugging ya but is one of you able to see if using the hotfixed jar on the server fixes the problem?

**Comment by Charwten** [comment] 2020-11-25 01:58
I'll be honest.. I do not know what you mean by hotfixed jar lmao! What do you mean?

**Comment by How-Bout-No** [comment] 2020-11-25 02:12
The jar in the zip from earlier with the crashing fix, that you used in singleplayer.

**Comment by Charwten** [comment] 2020-11-25 02:15
Oh yeah! Sorry about that! I tried it on the server and I had the same problem with the crash

**Comment by How-Bout-No** [comment] 2020-11-25 21:01
Ok it seems the method I use to check biomes for the texture variants just... doesn't work on a server? I don't know of any fixes as I've meddled with it for about a day and I think it might just be beyond my knowledge. I'll probably just subtract the Kraken variants for now, which isn't ideal at all but it's the quickest fix so the next release isn't too delayed.

**Comment by judicius** [comment] 2020-12-02 17:39
getting the same issue with Inferno Entity. Will attempt to turn off variants to see if CTD stops on the server

**Comment by How-Bout-No** [comment] 2020-12-02 20:52
> getting the same issue with Inferno Entity. Will attempt to turn off variants to see if CTD stops on the server.
> 
> Disabling the variants worked. You may want to default them to false until theres a solution and comment that they will CTD a client connected to a server.

Thank you for this! Looks like I might have to incorporate a different method for biome variants. I suspect it could be related to how the Inferno and Kraken variants are configurable, while the Hunger's is hardcoded, as I haven't had any crash reports related to Hunger rendering despite it having texture variants.

**Comment by judicius** [comment] 2020-12-02 23:36
heres a crashlog in case it sheds some light
https://pastebin.com/0fRrSwhY
and the CTD error is AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by How-Bout-No** [comment] 2020-12-06 21:47
Sort of fixed in 32c7e7b. With the way I now do biome variants to prevent server crashes, that is checking the block it spawns on instead of the biome, the Kraken's variants won't work since it spawns in water but Inferno and Hunger will work with this method. For now, Kraken variants will still be disabled until I can find a better method. I'll close this issue for now, but that does not mean I won't keep trying to find a compatible method.

**Closed by How-Bout-No** 2020-12-06 21:47 UTC
Labels: bug
