### ISSUE TITLE
Server start missing registry fixer errors

### ISSUE THREAD

**Issue by serioos** [How-Bout-No/Outvoted#108] opened 2021-11-25 08:25 UTC
The server throws these errors on Fabric.

[10:37:47] [main/ERROR]: No data fixer registered for outvoted:wildfire
[10:37:47] [main/ERROR]: No data fixer registered for outvoted:glutton
[10:37:47] [main/ERROR]: No data fixer registered for outvoted:barnacle
[10:37:47] [main/ERROR]: No data fixer registered for outvoted:glare
[10:37:47] [main/ERROR]: No data fixer registered for outvoted:copper_golem

**Comment by How-Bout-No** [comment] 2021-11-25 16:14
Duplicate of #88. These errors can be ignored and don't affect anything.

**Closed as completed by How-Bout-No** 2021-11-25 16:14 UTC
Labels: bug, duplicate
